### ISSUE TITLE
Markdown in post with code has scrollbar - need correct style / remove

### ISSUE THREAD

**Issue by mynameisek** [adcpm/busy#191]
![image](https://cloud.githubusercontent.com/assets/8390894/21326999/56fec090-c62d-11e6-8116-cfc3248b3815.png)

should be at least like steemit or improved style  (without bar)

![image](https://cloud.githubusercontent.com/assets/8390894/21327033/7598a7fa-c62d-11e6-9c40-227c2f9d06e5.png)

**Comment by nil1511** [comment]
both have same behaviour. on steemit it looks different because the post are wider so it fits. Try reducing the browser window.
I think it is correct behaviour. If we wrap code then it will change its style which should not happen for code. http://stackoverflow.com/q/41082878/2329027 on stackoverflow if it is wrap it will be unreadable.
