### ISSUE TITLE
Next Story link disappears after reloading the current page

### ISSUE THREAD

**Issue by tibonova** [adcpm/busy#257]
First, I had experienced #252 after I hit reload, and the previous post loaded, and I only spotted the link disappearance when I wanted to reproduce the bug. (I didn't know the URL thing was already reported. :smile: ) 
After that I've tried it on a freshly and "normally" loaded post, and the same thing happened.

**Comment by p0o** [comment]
It's not actually a bug. There are differences between a post page that is clicked from the feed and a post page that is opened directly (same thing as reloading the post page)

Next Post currently support the first type of posts (we call them Post Modal) since it is relying on the data that is loaded on feed to guide users to the next story and in the direct opened posts that data does not exist.

However I think we need `next story` to independently load more articles in the same category of article to provide this feature in all situations for increased integrity and for the same reason I keep this issue open for later discussion.
