### ISSUE TITLE
Comments Submit on Enter

### ISSUE THREAD

**Issue by kharoof** [adcpm/busy#313]
When you are writing a comment and you hit enter it submits. I think the UX would be better with a  submit button. I have submitted comments by accident that weren't ready.

**Comment by tibonova** [comment]
This issue is even more serious until users could edit comments.

I suggest let the users decide that how they want to use enter. A little checkbox ( :white_check_mark:  enter = post; :negative_squared_cross_mark: enter = new line) with the mentioned button could solve the problem. 

This problem also affects many users who are not used to shift+enter, and want a line-break/empty line in their comments.

**Comment by p0o** [comment]
But it's a common behavior in many platforms including Facebook. `Shift + Enter` is for adding line breaks and enter is for submitting the comment.

**Comment by kharoof** [comment]
It might be common behaviour but it means you can submit stuff which you cannot change. Unlike other platforms this is being entered on a blockchain. Different platforms let you edit what you write. Even if you edit your comment on Steemit your original comment will always be there. 

As @tibonova suggested some form of checkbox or at least pop up are you sure you want to submit would work great.

**Comment by adcpm** [comment]
IMO it would be more confusing to have a checkbox on comment form. We have to chose rather using enter for submit (Facebook style) or button for submit (GitHub style) and enable edition. But the chat can only be with enter for submit.

**Comment by p0o** [comment]
I suggest an option for changing text submission on both comment and chat from `Enter` to `Shift + Enter` which AFAIK is used in [meetup](http://meetup.cpm)

**Comment by snowflake11** [comment]
@p0o  your suggestion is way too geeky :-) 

I think the best would be a submit button.  Even if many people know about shift+enter it still inconvenient and feels a bit like a hack because you have to press 2 keys simultaneously

An option I would like to see in settings though is the ability to change my online statut from green to invisble, away,busy,etc...

**Comment by mynameisek** [comment]
Here is my opinion:
It all depends on the user experience we want to incentivize for Busy.
as Steemit is presented like a platform where you can post good and unique content to get rewarded for it, it involves also quality comments which most of times are longer post than usual Facebook comment, and quick reactions.
Those long comment, which are actually posts on the blockchain, require minimum writing effort and is usually better for user experience to have a Submit button than Enter key to Submit like Facebook.
We can conclude that the reason for which Facebook goes for Enter to post, is because they incentivize short, and de-facto, low quality comments, than longer posts.

To have a rich debate you actually need (very often) to use "Enter" several times, than to comment something simple like "Thank you for your support! Glad you like my post!" +Enter.

This seems like the choice we will make actually define, and incentivize the quality comment /or not, and the way we want people to comment.

**My preference goes for a Submit button on Comments+Post, and Enter for Chat/Message.**

**Comment by snowflake11** [comment]
> My preference goes for a Submit button on Comments+Post, and Enter for Chat/Message.

Agreed

Posts already have a publish button btw :)

**Comment by clayop** [comment]
This is blockchain and once a message is recorded, it cannot permanently deleted. Submit by enter key would cause more mistakes than by submit button.

**Comment by kharoof** [comment]
Chat
Submit on enter is perfect for Chat. Its intuitive and what you would expect. 
Comments
For comments its the opposite, you probably want to format comments indent etc so it makes sense that you need to click a button there before submitting. The design here on github is perfect for comments.

**Comment by clayop** [comment]
Side note.. I just made a mistake with comment. I meant to change the line but it was submitted. I strongly eager to have submit button in post and comment as @mynameisek suggested.
